26914 clicking on image should not result in download
AAFC-BICoE/dina-ui pull request #687
Opened 2022-03-16 17:30 UTC by johnphan96

2022-03-18 20:29 UTC, brandonandre requested changes
I provided some feedback for this ticket below. Just a few tweaks and it should be ready for prime time. 🎯

This will be a very helpful feature for users! 

Brandon

2022-03-18 20:29 UTC, brandonandre commented on packages/dina-ui/pages/object-store/metadata/fullscreenPreview .tsx
> +);
I think this file can be removed, I don't think it's being used by anything.

2022-03-18 20:29 UTC, brandonandre commented on packages/dina-ui/pages/object-store/object/view.tsx
>              <div className="col-md-4">
I would remove this `col-md-4` className. This restricts the size of the preview to be  only about a quarter of the screen. 

Before:

![image](https://user-images.githubusercontent.com/3820842/159078302-a3e6b109-5e37-4041-8b6a-22eb16118113.png)

After:

![image](https://user-images.githubusercontent.com/3820842/159078383-40ad38b0-d540-4080-8f0c-5cb4f544b4b0.png)

Then the image will always display as the true size and also in the center 👍

2022-03-22 13:48 UTC, cgendreau commented on packages/dina-ui/components/object-store/file-view/FileView.tsx
> +            }}
It would be preferable to do nothing. There is already a link to download below the preview.

2022-03-23 20:51 UTC, brandonandre approved these changes
Clicking an image will open a new tab with a full sized preview. 👍 
Clicking a document or any other file will do nothing, use the download button below. 👍 

Perfect!

Approved.

2022-03-23 20:52 UTC, merged